import { useState } from 'react';
import OverflowMenu from '../components/ui/OverflowMenu';
import { Link } from 'react-router-dom';
import { useNotesList } from '../features/notes/hooks/useNotesList';
import '../features/notes/notes.css';
import { jobLabel } from '../features/notes/labels';
export default function NotesPage() {
    const { params, setParams, view, page, error, loading, busy, undo, setUndo, setRefresh, filter, changeStatus, filterOptions, filterError } = useNotesList();
    const [filtersOpen, setFiltersOpen] = useState(false);
    const filtered = ['q', 'subject', 'book_id', 'chapter_ref_id'].some(key => Boolean(params.get(key)));
    const clearFilters = () => { const next = new URLSearchParams(params); ['q', 'subject', 'book_id', 'chapter_ref_id', 'cursor'].forEach(key => next.delete(key)); setParams(next); };
    return <div className="management-workspace notes-workspace"><header className="app-page-header note-page-header window-drag-region"><h1>笔记</h1></header><div className="note-list-controls"><div className="note-list-toolbar"><nav className="note-tabs" aria-label="笔记视图">{[['saved', '已保存'], ['drafts', '草稿'], ['archived', '已归档']].map(([value, label]) => <button className={`app-ghost-button ${view === value ? 'is-selected' : ''}`} aria-pressed={view === value} key={value} onClick={() => filter('view', value)}>{label}</button>)}</nav>{view !== 'drafts' && <><label className="note-search"><input aria-label="搜索笔记" value={params.get('q') || ''} onChange={e => filter('q', e.target.value)} placeholder="搜索标题、摘要或标签"/></label><button className="app-ghost-button" aria-expanded={filtersOpen} onClick={() => setFiltersOpen(v => !v)}>筛选{filtered ? ' · 已启用' : ''}</button>{filtered && <button className="app-ghost-button" onClick={clearFilters}>清除筛选</button>}</>}</div>{view !== 'drafts' && filtersOpen && <div className="note-filters"><label>学科<input aria-label="笔记学科" value={params.get('subject') || ''} onChange={e => filter('subject', e.target.value)} placeholder="全部学科"/></label><label>教材<select value={params.get('book_id') || ''} onChange={e => filter('book_id', e.target.value)}><option value="">全部教材</option>{filterOptions.books.map(c => <option key={c.book_id} value={c.book_id}>{c.name}</option>)}</select></label><label>章节<select value={params.get('chapter_ref_id') || ''} onChange={e => filter('chapter_ref_id', e.target.value)}><option value="">全部章节</option>{filterOptions.chapter_refs.map(c => <option key={c.chapter_ref_id} value={c.chapter_ref_id}>{c.title_snapshot} · {c.canonical_hash?.slice(0, 6) || '历史元数据'}</option>)}</select></label></div>}</div><div className="note-scroll"><div className="note-list">
    {filterError && <p className="note-caption" role="status">{filterError}</p>}{error && <div role="alert" className="note-warning"><p>{error}</p><button className="app-secondary-button" onClick={() => setRefresh(v => v + 1)}>重新读取</button></div>}{undo && <p role="status">{undo.status === 'active' ? '已归档' : '已恢复'} · <button className="app-ghost-button" disabled={busy} onClick={() => { void changeStatus(undo.id, undo.revision, undo.status); setUndo(null); }}>撤销</button></p>}
    {loading ? <p role="status">正在读取笔记…</p> : page.items.length === 0 ? <div className="note-empty"><h2>{params.get('q') || params.get('subject') || params.get('book_id') || params.get('chapter_ref_id') ? '没有符合筛选条件的笔记' : view === 'drafts' ? '暂无待整理草稿' : view === 'archived' ? '暂无归档笔记' : '还没有保存的笔记'}</h2>{filtered ? <><p>调整搜索或筛选后再试。</p><button className="app-secondary-button" onClick={clearFilters}>清除筛选</button></> : view === 'archived' ? <p>归档的笔记会显示在这里。</p> : <><p>在会话三点菜单中选择“整理为笔记”，审阅后保存。</p><Link className="app-primary-button" to="/">回到学习</Link></>}</div> : page.items.map(item => { const isNote = 'revision' in item; return <article className="note-list-item" key={item.id}><div className="note-list-item-main"><Link className="note-list-title" to={`/notes/${isNote ? '' : 'drafts/'}${item.id}`}>{item.title}</Link>{isNote && item.abstract && <p>{item.abstract}</p>}<p className="note-caption">{new Date(item.updated_at).toLocaleString()} {isNote ? ` · ${item.origins[0].title_snapshot}` : ` · ${item.job ? jobLabel[item.job.status] || item.job.status : ({ preparing: '待恢复', editable: '可编辑草稿' })[item.status] || item.status}`}</p>{isNote && item.chapter_refs.map(c => <span className="note-caption" key={c.chapter_ref_id}>{c.title_snapshot} · </span>)}</div>{isNote && <OverflowMenu label={`${item.title}的更多操作`}>{close => <button role="menuitem" disabled={busy} onClick={() => { close(); void changeStatus(item.id, item.revision, item.status === 'active' ? 'archived' : 'active'); }}>{item.status === 'active' ? '归档' : '恢复'}</button>}</OverflowMenu>}</article>; })}
    <div className="note-actions">{params.get('cursor') && <button className="app-secondary-button" onClick={() => filter('cursor', '')}>第一页</button>}{page.next_cursor && <button className="app-secondary-button" onClick={() => { const next = new URLSearchParams(params); next.set('cursor', page.next_cursor!); setParams(next); }}>下一页</button>}</div>
  </div></div></div>;
}
