"""Utilities for cleaning Markdown + LaTeX generated by LLMs."""
from __future__ import annotations

import re

_CHINESE_RE = re.compile(r'[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]')
_MATH_ENV_RE = re.compile(
    r'(\\begin\{(?:aligned|align|gathered|gather|cases|matrix|pmatrix|bmatrix|vmatrix|Vmatrix|array|split|equation)\}[\s\S]*?\\end\{(?:aligned|align|gathered|gather|cases|matrix|pmatrix|bmatrix|vmatrix|Vmatrix|array|split|equation)\})'
)


def sanitize_latex(text: str) -> str:
    """Normalize common Markdown + LaTeX delimiter issues before rendering."""
    text = _normalize_latex_text(str(text or ""))
    text = _strip_latex_spacing_options(text)
    text = _convert_tex_delimiters(text)
    text = _repair_multiline_inline_math(text)
    text = _wrap_bare_temperature_fragments(text)
    text = _wrap_bare_latex_lines(text)
    text = _wrap_bare_math_environments(text)
    text = _remove_inline_delimiters_inside_display_math(text)
    text = _remove_empty_math(text)
    return _balance_math_delimiters(text)


def _normalize_latex_text(text: str) -> str:
    return (
        text.replace('\r\n', '\n')
        .replace('\uff04', '$')
        .replace('\ufe69', '$')
        .replace('\\\\[', '\\[')
        .replace('\\\\]', '\\]')
        .replace('\\\\(', '\\(')
        .replace('\\\\)', '\\)')
    )


def _strip_latex_spacing_options(text: str) -> str:
    # Convert line breaks like \\[4pt] to a plain LaTeX line break.
    return re.sub(r'\\{1,2}\s*\[(?:\d+(?:\.\d+)?)(?:pt|em|ex|mm|cm|in)\]', r'\\\\', text)


def _convert_tex_delimiters(text: str) -> str:
    text = re.sub(r'(?<!\\)\\\((.+?)(?<!\\)\\\)', r'$\1$', text, flags=re.DOTALL)
    text = re.sub(r'(?<!\\)\\\[(.+?)(?<!\\)\\\]', r'$$\1$$', text, flags=re.DOTALL)
    return text


def _single_dollar_positions(line: str) -> list[int]:
    return [
        index for index, char in enumerate(line)
        if char == '$'
        and (index == 0 or line[index - 1] != '$')
        and (index + 1 >= len(line) or line[index + 1] != '$')
        and not _is_escaped(line, index)
    ]


def _repair_multiline_inline_math(text: str) -> str:
    """Inline math cannot span Markdown paragraphs; repair isolated edge dollars per line."""
    result: list[str] = []
    in_fence = False
    in_block_math = False
    for line in text.split('\n'):
        stripped = line.strip()
        if stripped.startswith('```'):
            in_fence = not in_fence
            result.append(line)
            continue
        if not in_fence and line.count('$$') % 2:
            in_block_math = not in_block_math
        if in_fence or in_block_math:
            result.append(line)
            continue
        positions = _single_dollar_positions(line)
        if len(positions) == 1:
            position = positions[0]
            if not line[:position].strip():
                line = line.rstrip() + '$'
            elif not line[position + 1:].strip():
                line = '$' + line.lstrip()
        result.append(line)
    return '\n'.join(result)


_BARE_TEMPERATURE_RE = re.compile(
    r'(?<![$\\])(?P<value>(?:[A-Za-z][A-Za-z0-9_{}]*\s*=\s*)?[-+]?\d+(?:\.\d+)?\s*\^?\\circ\s*(?:\\text\{C\}|C))(?![$A-Za-z])'
)


def _wrap_bare_temperature_fragments(text: str) -> str:
    protected, tokens = _protect_segments(text)
    protected = _BARE_TEMPERATURE_RE.sub(lambda match: f"${match.group('value')}$", protected)
    return _restore_segments(protected, tokens)


def _wrap_bare_latex_lines(text: str) -> str:
    """Wrap formula-only lines containing TeX commands, including legacy answers."""
    protected, tokens = _protect_segments(text)
    result: list[str] = []
    in_fence = False
    for line in protected.split('\n'):
        stripped = line.strip()
        if stripped.startswith('```'):
            in_fence = not in_fence
        if (
            not in_fence
            and stripped
            and '$' not in stripped
            and re.search(r'\\(?:approx|text|circ|frac|sqrt|sum|int|Delta|theta|lambda|mu|sigma|mathrm|mathbf)\b', stripped)
            and _find_chinese_outside_braces(stripped) is None
        ):
            prefix = line[:len(line) - len(line.lstrip())]
            line = f"{prefix}${stripped}$"
        result.append(line)
    return _restore_segments('\n'.join(result), tokens)


def _remove_inline_delimiters_inside_display_math(text: str) -> str:
    def clean(match: re.Match) -> str:
        body = re.sub(r'(?<!\\)(?<!\$)\$(?!\$)', '', match.group(1))
        return f"$${body}$$"

    return re.sub(r'(?<!\\)\$\$([\s\S]*?)(?<!\\)\$\$', clean, text)


def _protect_segments(text: str) -> tuple[str, list[str]]:
    tokens: list[str] = []

    def protect(match: re.Match) -> str:
        token = f"@@LATEX_PROTECTED_{len(tokens)}@@"
        tokens.append(match.group(0))
        return token

    patterns = [
        r'```[\s\S]*?```',
        r'`[^`]*`',
        r'(?<!\\)\$\$[\s\S]*?(?<!\\)\$\$',
        r'(?<!\\)(?<!\$)\$(?!\$)(?:\\.|[^$\\])*?(?<!\\)(?<!\$)\$(?!\$)',
    ]
    protected = text
    for pattern in patterns:
        protected = re.sub(pattern, protect, protected)
    return protected, tokens


def _restore_segments(text: str, tokens: list[str]) -> str:
    for idx, token in enumerate(tokens):
        text = text.replace(f"@@LATEX_PROTECTED_{idx}@@", token)
    return text


def _wrap_bare_math_environments(text: str) -> str:
    protected, tokens = _protect_segments(text)
    protected = _MATH_ENV_RE.sub(lambda m: f"$$\n{m.group(1)}\n$$", protected)
    return _restore_segments(protected, tokens)


def _remove_empty_math(text: str) -> str:
    # Newlines separate Markdown math blocks. Treat only horizontal whitespace
    # as an empty expression, otherwise `$\n\n$` can erase two valid boundaries.
    text = re.sub(r'(?<!\\)\$\$[ \t]*(?<!\\)\$\$', '', text)
    return re.sub(r'(?<!\\)(?<!\$)\$(?!\$)[ \t]*(?<!\\)(?<!\$)\$(?!\$)', '', text)


def _is_escaped(text: str, index: int) -> bool:
    slash_count = 0
    i = index - 1
    while i >= 0 and text[i] == '\\':
        slash_count += 1
        i -= 1
    return slash_count % 2 == 1


def _find_chinese_outside_braces(text: str) -> int | None:
    depth = 0
    escaped = False
    for idx, ch in enumerate(text):
        if escaped:
            escaped = False
            continue
        if ch == '\\':
            escaped = True
            continue
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth = max(0, depth - 1)
        elif depth == 0 and _CHINESE_RE.match(ch):
            return idx
    return None


def _first_non_whitespace(text: str) -> int | None:
    for idx, ch in enumerate(text):
        if not ch.isspace():
            return idx
    return None


def _next_unescaped(text: str, token: str) -> int:
    start = 0
    while True:
        idx = text.find(token, start)
        if idx == -1:
            return -1
        if not _is_escaped(text, idx):
            return idx
        start = idx + len(token)


def _balance_math_delimiters(text: str) -> str:
    result: list[str] = []
    i = 0
    n = len(text)

    while i < n:
        if text.startswith(r'\$', i):
            result.append(r'\$')
            i += 2
            continue

        if text.startswith('$$', i) and not _is_escaped(text, i):
            rest = text[i + 2:]
            first = _first_non_whitespace(rest)
            if first is not None and _CHINESE_RE.match(rest[first]):
                close = _next_unescaped(rest, '$$')
                if close >= 0:
                    result.append(rest[:close])
                    i += 2 + close + 2
                else:
                    result.append(rest)
                    i = n
                continue

            close = _next_unescaped(rest, '$$')
            chinese = _find_chinese_outside_braces(rest)
            if close >= 0 and (chinese is None or close < chinese):
                result.extend(['$$', rest[:close], '$$'])
                i += 2 + close + 2
            elif chinese is not None:
                math_content = rest[:chinese]
                stripped = math_content.rstrip()
                result.extend(['$$', stripped, '$$', math_content[len(stripped):]])
                i += 2 + chinese
            else:
                result.extend(['$$', rest, '$$'])
                i = n
            continue

        if text[i] == '$' and not _is_escaped(text, i):
            rest = text[i + 1:]
            first = _first_non_whitespace(rest)
            if first is not None and _CHINESE_RE.match(rest[first]):
                close = _next_unescaped(rest, '$')
                if close >= 0:
                    result.append(rest[:close])
                    i += 1 + close + 1
                else:
                    result.append(rest)
                    i = n
                continue

            close = _next_unescaped(rest, '$')
            chinese = _find_chinese_outside_braces(rest)
            if close >= 0 and (chinese is None or close < chinese):
                result.extend(['$', rest[:close], '$'])
                i += 1 + close + 1
            elif chinese is not None:
                math_content = rest[:chinese]
                stripped = math_content.rstrip()
                result.extend(['$', stripped, '$', math_content[len(stripped):]])
                i += 1 + chinese
            else:
                result.extend(['$', rest, '$'])
                i = n
            continue

        result.append(text[i])
        i += 1

    return ''.join(result)
